module.exports=function (grunt) {
    grunt.initConfig({
        pkg:grunt.file.readJSON('package.json'),
        concat:{
            base:{
                options:{
                    banner:";",
                },
                src:[
                    'static/lib/js/jquery-1.12.3.min.js',
                    'static/lib/js/vue.min.js',
                    'static/js/dealCSRF.js',
                    'static/DialogBox/MyDialogBox/js/jquery.myDialogBox-1.0.js',
                    'static/js/common.js',
                ],
                dest:'static/dist/js/base.js',
            },
            books:{
                options:{
                    banner:";",
                },
                src:[
                    'static/dist/js/base.js',
                    'static/js/books.js',
                ],
                dest:'static/dist/js/books.js',
            },
            homepage:{
                options:{
                    banner:";",
                },
                src:[
                    'static/dist/js/base.js',
                    'static/js/homepage.js',
                ],
                dest:'static/dist/js/homepage.js',
            },
            passages:{
                options:{
                    banner:";",
                },
                src:[
                    'static/dist/js/base.js',
                    'static/js/passages.js',
                ],
                dest:'static/dist/js/passages.js',
            },
            passage:{
                options:{
                    banner:";",
                },
                src:[
                    'static/dist/js/base.js',
                    'static/js/passage.js',
                ],
                dest:'static/dist/js/passage.js',
            },
            ToDoList:{
                options:{
                    banner:";",
                },
                src:[
                    'static/lib/js/jquery-1.12.3.min.js',
                    'static/lib/js/vue.min.js',
                    'static/js/dealCSRF.js',
                    'static/js/ToDoList/ToDoList.js',
                ],
                dest:'static/dist/js/ToDoList.js',
            },
        },
        uglify:{
            options:{
                    banner:"/*min*/",
                },
            blog:{
                files:{
                    'static/dist/js/books.min.js':['static/dist/js/base.js','static/js/book.js'],
                    'static/dist/js/homepage.min.js':['static/dist/js/base.js','static/js/homepage.js'],
                    'static/dist/js/passages.min.js':['static/dist/js/base.js','static/js/passages.js'],
                    'static/dist/js/passage.min.js':['static/dist/js/base.js','static/js/passage.js'],
                }
            },
            ToDoList:{
                files:{
                    'static/dist/js/ToDoList.min.js':[
                        'static/lib/js/jquery-1.12.3.min.js',
                        'static/lib/js/vue.min.js',
                        'static/js/dealCSRF.js',
                        'static/js/ToDoList/ToDoList.js',
                    ],
                }
            }

        },
        cssmin:{
            options:{
                keepSpecialComments:0,
            },
            blog:{
                files:{
                    'static/dist/css/base.min.css':['static/css/common.css','static/DialogBox/MyDialogBox/css/box.css'],
                    'static/dist/css/homepage.min.css':['static/dist/css/base.min.css','static/css/homepage.css','static/css/passages.css'],
                    'static/dist/css/passages.min.css':['static/dist/css/base.min.css','static/css/passages.css'],
                    'static/dist/css/books.min.css':['static/dist/css/base.min.css','static/css/books.css'],
                    'static/dist/css/passage.min.css':['static/dist/css/base.min.css','static/css/passages.css','static/css/passage.css',],
                }
            },
            ToDoList:{
                files:{
                    'static/dist/css/ToDoList.min.css':['static/css/ToDoList/ToDoList.css','static/css/ToDoList/note.css'],
                }
            }
        },
    });

    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-cssmin');

    grunt.registerTask('default',['concat','uglify','cssmin']);
};

